### ISSUE TITLE
Scrolling up happens when adding a block to your page

### ISSUE THREAD

**Issue by arne-vdw** [timmyomahony/craft-matrix-field-preview#106]
Cool plugin to use both neo and preview of blocks in a website, only we have a bug when adding blocks.
When a neo block is added or when closing the overlay without adding a block, the edit page continues to scroll up and focus on the page title field.
Does anyone have an idea how to fix this?

Matrix Field Preview | 4.0.5
-- | --
Neo | 3.7.9
Craft |  4.4.13

**Comment by timmyomahony** [comment]
I've been trying a few ways to fix this but it's a confusing one. Still working on it anyway and should have a fix soon.

**Comment by timmyomahony** [comment]
This should be fixed in the new version 5.0.0 of the plugin, just released.
