### ISSUE TITLE
"Add block above" in neo fields is not working

### ISSUE THREAD

**Issue by timmyomahony** [timmyomahony/craft-matrix-field-preview#112]
The button is inserted OK and the modal shows up, but when adding a new block, it gets added _below_ the block that triggered the request, not above

**Comment by yannkost** [comment]
Same here, in fact, it doesn't matter, where the 'add bloc above' has been triggered, but the new bloc will be added at the end.

**Comment by timmyomahony** [comment]
This should be fixed in version 5.0.0 just released
