### ISSUE TITLE
"Enabled" block setting not supported for Neo blocks

### ISSUE THREAD

**Issue by turnstylerj** [timmyomahony/craft-matrix-field-preview#118]
In Neo, it's possible to disable blocks:

![2023-11-14 at 15 56 50](https://github.com/timmyomahony/craft-matrix-field-preview/assets/42223501/1baefb72-df40-4552-90c6-914be34a32aa)

When a block is disabled, however, it still shows as available in the Matrix Field Preview selector. Ideally, it would retain its settings/configuration but not display.

**Comment by timmyomahony** [comment]
Hi @turnstylerj good suggestion, I'll look into filtering out disabled blocks.

**Comment by timmyomahony** [comment]
Fixed in version 4.1.3, thanks to @ttempleton
