### ISSUE TITLE
Can't reorder blocks

### ISSUE THREAD

**Issue by daltonrooney** [timmyomahony/craft-matrix-field-preview#127]
When I try to reorder a matrix block using the drag handle, I get a console error: `TypeError: null is not an object (evaluating 't.target.querySelectorAll')` and my change is not saved.

**Comment by timmyomahony** [comment]
Apologies for the delay here. I assume this was with the Craft 4 version, using matrix fields (as opposed to Neo fields)? There's a new version 5.0 out now that might address the issue, in the meantime could you let me know what version you were using?

**Comment by daltonrooney** [comment]
That's right, it's the Craft 4 version. We haven't moved too many of our existing sites to Craft 5 yet, any chance of a back-port to the Craft 4 version?

It's not something that will come up often for us since we're building new sites on Craft 5, but it would be nice to be able to edit the sort order for some of our existing sites if we decide to add new blocks.

**Comment by timmyomahony** [comment]
Happy to add a fix to version 4, but I can't replicate the issue at the moment. What version of Craft and the plugin are you using? Also, what other plugins have you got installed?

The Matrix Field Preview doesn't use `querySelectorAll` so I'm wondering where that's coming from. 

Just to confirm, here's what I'm doing (Craft `4.11.1` and version `4.1.3` of the plugin):

![CleanShot 2024-08-08 at 20 38 26](https://github.com/user-attachments/assets/f5e31633-1864-408c-9bd5-c33cc3be413a)

**Comment by timmyomahony** [comment]
Just to follow up here, I wonder is there another plugin injecting some JS/CSS onto control panel pages?

**Comment by daltonrooney** [comment]
Thanks for the follow-up @timmyomahony. This appears to have been an older Craft CMS issue in Safari only, which may be why you had trouble reproducing the issue. It was fixed in Craft 4.8.8: https://github.com/craftcms/cms/blob/4.x/CHANGELOG.md#488---2024-04-09

Sorry to bother you with this!
