### ISSUE TITLE
Enabling/disabling the preview button when "max blocks" is reached isn't supported

### ISSUE THREAD

**Issue by timmyomahony** [timmyomahony/craft-matrix-field-preview#71]
> Enabling/disabling the preview button when "max blocks" is reached isn't supported

**Comment by martinstarecek** [comment]
Hi @timmyomahony any new in this bug?

**Comment by timmyomahony** [comment]
@martinstarecek this should be supported for the default Matrix fields. It was added in a previous update (1.0.7 and 1.1.0). Are you noticing a situation where this isn't being respected? Neo's min/max blocks aren't currently supported.

**Comment by timmyomahony** [comment]
@martinstarecek I realise you might have meant with Neo? If so, I've created a new issue to track here:

https://github.com/timmyomahony/craft-matrix-field-preview/issues/124
